AWSTemplateFormatVersion: "2010-09-09"
Description: GC-CloudFormation deployment pipelines template

Resources:
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: "GC-repo"
      RepositoryDescription: "gc Repository for CFN infrastructure code."

Outputs:
  Group3CodeCommitRepoARN:
    Description: ARN of the CodeCommit Repository
    Value: !GetAtt CodeCommitRepository.Arn

  
